# @package _global_

model:
  name: microsoft/trocr-small-handwritten
  checkpoint_dir: null
  freeze_encoder: false

training:
  max_target_length: 50
  epochs: 40
  batch_size: 32
  eval_batch_size: 32
  gradient_accumulation_steps: 1
  save_strategy: epoch
  save_total_limit: 3
  num_workers: 4
  seed: 1111
  max_steps: -1
  no_fp16: false
