name: trocr-encoder-decoder-ablation
project: OCR_pretraining
entity: personal-space-astha
method: grid

metric:
  name: eval/cer
  goal: minimize

program: src.train.trocr
command:
  - ${env}
  - ${interpreter}
  - -m
  - src.train.trocr
  - wandb.enabled=true
  - wandb.name=null
  - training.epochs=40
  - training.checkpoint_top_k=1

parameters:
  experiment:
    values:
      - base_encoder_trained_lora_no_decoder_rand
      - base_encoder_frozen_lora_no_decoder_trained
      - base_encoder_frozen_lora_trained_decoder_trained
      - base_encoder_trained_lora_no_decoder_trained
      - base_encoder_frozen_lora_trained_decoder_rand
